using System.Text;
using LifeDash.Api.Data;
using LifeDash.Api.Endpoints;
using LifeDash.Api.Models;
using LifeDash.Api.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using System.Security.Claims;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);

// ---------- login allow-list / shared logins (generated by the deploy workflow) ----------
builder.Configuration.AddJsonFile("appsettings.Auth.json", optional: true, reloadOnChange: false);

// ---------- database ----------
var conn = builder.Configuration.GetConnectionString("Default")
           ?? throw new InvalidOperationException("ConnectionStrings:Default is missing.");
builder.Services.AddDbContext<LifeDashContext>(o => o.UseSqlServer(conn));

// ---------- auth ----------
var jwt = builder.Configuration.GetSection("Jwt").Get<JwtOptions>() ?? new JwtOptions();
if (string.IsNullOrWhiteSpace(jwt.Key) || jwt.Key.Length < 32)
    throw new InvalidOperationException("Jwt:Key must be at least 32 characters. Set it in appsettings or as an environment variable.");

builder.Services.AddSingleton(jwt);
builder.Services.AddScoped<TokenService>();
builder.Services.AddScoped<DeadlineEngine>();
builder.Services.AddSingleton<IAuditLogWriter, AuditLogWriter>();
builder.Services.AddHttpContextAccessor();
builder.Services.Configure<ReminderEmailOptions>(builder.Configuration.GetSection("ReminderEmail"));
builder.Services.Configure<MailTrackingOptions>(builder.Configuration.GetSection("MailTracking"));
builder.Services.AddSingleton<MicrosoftMailAuthService>();
builder.Services.AddScoped<ImapPackageScanner>();
builder.Services.AddScoped<PackageSyncService>();
builder.Services.AddScoped<ImapAppointmentScanner>();
builder.Services.AddScoped<AppointmentSyncService>();
builder.Services.AddSingleton<ReminderEmailWorker>();
builder.Services.AddHostedService(services => services.GetRequiredService<ReminderEmailWorker>());

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o =>
    {
        o.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = jwt.Issuer,
            ValidAudience = jwt.Audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwt.Key)),
            NameClaimType = "name",
            ClockSkew = TimeSpan.FromMinutes(2)
        };
    });
builder.Services.AddAuthorization();

// ---------- cors ----------
var origins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
              ?? new[] { "http://localhost:5173" };
builder.Services.AddCors(o => o.AddPolicy("spa", p => p
    .WithOrigins(origins)
    .AllowAnyHeader()
    .AllowAnyMethod()));

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddProblemDetails();

var app = builder.Build();

app.Use(async (ctx, next) =>
{
    var sw = Stopwatch.StartNew();
    await next();
    sw.Stop();

    if (!ctx.Request.Path.StartsWithSegments("/api")) return;

    var audit = ctx.RequestServices.GetRequiredService<IAuditLogWriter>();
    var raw = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier) ?? ctx.User.FindFirstValue("sub");
    var userId = int.TryParse(raw, out var uid) ? uid : (int?)null;
    audit.Write(new
    {
        ts = DateTimeOffset.UtcNow,
        eventType = "request",
        userId,
        method = ctx.Request.Method,
        path = ctx.Request.Path.Value,
        status = ctx.Response.StatusCode,
        ms = sw.ElapsedMilliseconds,
        ip = ctx.Connection.RemoteIpAddress?.ToString()
    });
});

// ---------- fix the seeded demo password hash once ----------
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<LifeDashContext>();
    try
    {
        await db.Database.ExecuteSqlRawAsync("""
            IF COL_LENGTH('dbo.Trips', 'StartPlace') IS NULL
                ALTER TABLE dbo.Trips ADD StartPlace NVARCHAR(200) NULL;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            IF COL_LENGTH('dbo.Bookings', 'Direction') IS NULL
                ALTER TABLE dbo.Bookings ADD Direction NVARCHAR(20) NULL;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            IF COL_LENGTH('dbo.PackingItems', 'BookingId') IS NULL
                ALTER TABLE dbo.PackingItems ADD BookingId INT NULL;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PackingItems_Bookings')
                ALTER TABLE dbo.PackingItems ADD CONSTRAINT FK_PackingItems_Bookings
                    FOREIGN KEY (BookingId) REFERENCES dbo.Bookings(Id) ON DELETE SET NULL;
            """);

        var seeded = db.Users.FirstOrDefault(u => u.PasswordHash == "SEED");
        if (seeded is not null)
        {
            seeded.PasswordHash = PasswordHasher.Hash("demo1234");
            db.SaveChanges();
        }
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(ex, "Could not reach the database at startup. Run the SQL scripts first.");
    }
}

app.UseExceptionHandler();
app.UseStatusCodePages();

if (app.Configuration.GetValue("Swagger:Enabled", true))
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("spa");
app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/", () => Results.Ok(new { name = "Life Dashboard API", version = "1.0.0" }));
app.MapGet("/api/health", async (LifeDashContext db) =>
{
    var ok = await db.Database.CanConnectAsync();
    return ok ? Results.Ok(new { status = "healthy" })
              : Results.Json(new { status = "database unreachable" }, statusCode: 503);
});

app.MapPost("/api/jobs/reminders", async (HttpRequest request, IConfiguration configuration,
    ReminderEmailWorker reminders, CancellationToken ct) =>
{
    var expectedKey = configuration["ReminderTrigger:ApiKey"];
    var receivedKey = request.Headers["X-Reminder-Trigger"].ToString();
    if (string.IsNullOrWhiteSpace(expectedKey))
        return Results.Problem("ReminderTrigger:ApiKey is not configured.", statusCode: StatusCodes.Status503ServiceUnavailable);
    if (!string.Equals(receivedKey, expectedKey, StringComparison.Ordinal))
        return Results.Unauthorized();

    var result = await reminders.RunOnceAsync(ct);
    return result switch
    {
        ReminderRunResult.Completed => Results.Ok(new { status = "completed" }),
        ReminderRunResult.AlreadyRunning => Results.Ok(new { status = "already-running" }),
        _ => Results.Problem("Reminder run failed. Check the application logs.", statusCode: StatusCodes.Status500InternalServerError)
    };
}).ExcludeFromDescription();

// Scans the mailbox for Sendungen and Termine on a schedule (cron-job.org calls this every 6
// hours) so the existing manual "Postfach scannen" buttons keep working independently of this.
// Reuses the same shared secret as /api/jobs/reminders under a distinct header, since mailbox
// scanning is single-account and there's no logged-in user to attribute the results to on a
// scheduled call — MailTracking:OwnerUserId says which account to write into instead.
app.MapPost("/api/jobs/mail-scan", async (HttpRequest request, IConfiguration configuration,
    IOptions<MailTrackingOptions> mailOptions, PackageSyncService packageSync, AppointmentSyncService appointmentSync,
    LifeDashContext db, CancellationToken ct) =>
{
    var expectedKey = configuration["ReminderTrigger:ApiKey"];
    var receivedKey = request.Headers["X-MailScan-Trigger"].ToString();
    if (string.IsNullOrWhiteSpace(expectedKey))
        return Results.Problem("ReminderTrigger:ApiKey is not configured.", statusCode: StatusCodes.Status503ServiceUnavailable);
    if (!string.Equals(receivedKey, expectedKey, StringComparison.Ordinal))
        return Results.Unauthorized();

    var ownerUserId = mailOptions.Value.OwnerUserId;
    if (ownerUserId <= 0)
        return Results.Problem("MailTracking:OwnerUserId is not configured.", statusCode: StatusCodes.Status503ServiceUnavailable);

    try
    {
        var packages = await packageSync.SyncAsync(ownerUserId, full: false, db, ct);
        var appointments = await appointmentSync.SyncAsync(ownerUserId, db, ct);
        return Results.Ok(new
        {
            status = "completed",
            packages = new { packages.Scanned, packages.Added, packages.Updated },
            appointments = new { appointments.Scanned, appointments.Added, appointments.SkippedDuplicate },
        });
    }
    catch (Exception ex)
    {
        return Results.Problem(title: "Mail scan failed. Check the application logs.", detail: ex.Message, statusCode: StatusCodes.Status500InternalServerError);
    }
}).ExcludeFromDescription();

app.MapGet("/api/logs", (HttpContext ctx, IAuditLogWriter audit, int? take) =>
{
    var path = audit.GetPath();
    if (!File.Exists(path)) return Results.Ok(Array.Empty<object>());

    var raw = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier) ?? ctx.User.FindFirstValue("sub");
    if (!int.TryParse(raw, out var userId)) return Results.Unauthorized();

    var max = Math.Clamp(take ?? 200, 1, 1000);
    var lines = File.ReadLines(path)
        .Where(l => !string.IsNullOrWhiteSpace(l))
        .Reverse()
        .Take(5000)
        .Select(line =>
        {
            try
            {
                using var doc = JsonDocument.Parse(line);
                var root = doc.RootElement;
                if (!root.TryGetProperty("userId", out var uid)) return null;
                if (uid.ValueKind != JsonValueKind.Number || uid.GetInt32() != userId) return null;
                return line;
            }
            catch
            {
                return null;
            }
        })
        .Where(x => x is not null)
        .Take(max)
        .Select(x => JsonDocument.Parse(x!).RootElement.Clone())
        .ToArray();

    return Results.Ok(lines);
}).RequireAuthorization().WithTags("logs");

app.MapAuth();
app.MapLifeDash();

app.Run();
